Repository uccser/codewof, pull requests merged in 2020-04, with the labels that each got.

#196 codeWOF Gamification with changes
  codewof/__init__.py
  codewof/config/settings/base.py
  codewof/general/management/commands/sampledata.py
  codewof/programming/admin.py
  codewof/programming/codewof_utils.py
  codewof/programming/management/commands/backdate_points_and_badges.py
  codewof/programming/management/commands/load_badges.py
  codewof/programming/migrations/0003_auto_20190904_1810.py
  codewof/programming/migrations/0004_badge_badge_tier.py
  codewof/programming/migrations/0005_badge_parent.py
  codewof/programming/migrations/0006_profile_attempted_questions.py
  codewof/programming/migrations/0007_auto_20200409_1424.py
  codewof/programming/models.py
  codewof/programming/urls.py
  codewof/programming/views-old.txt
  codewof/programming/views.py
  codewof/static/img/icons/badges/icons8-attempt-made-black-50.png
  codewof/static/img/icons/badges/icons8-attempt-made-bronze-50.png
  codewof/static/img/icons/badges/icons8-attempt-made-gold-50.png
  codewof/static/img/icons/badges/icons8-attempt-made-silver-50.png
  codewof/static/img/icons/badges/icons8-badge-create-account-48.png
  codewof/static/img/icons/badges/icons8-calendar-14-50.png
  codewof/static/img/icons/badges/icons8-calendar-2-50.png
  codewof/static/img/icons/badges/icons8-calendar-21-50.png
  codewof/static/img/icons/badges/icons8-calendar-28-50.png
  codewof/static/img/icons/badges/icons8-calendar-7-50.png
  codewof/static/img/icons/badges/icons8-question-solved-black-50.png
  codewof/static/img/icons/badges/icons8-question-solved-bronze-50.png
  codewof/static/img/icons/badges/icons8-question-solved-gold-50.png
  codewof/static/img/icons/badges/icons8-question-solved-silver-50.png
  codewof/static/img/icons/icons8-star-64.png
  codewof/static/js/question_types/base.js
  codewof/static/scss/website.scss
  codewof/static/svg/icons8-points.svg
  codewof/templates/base.html
  codewof/templates/programming/badge_card.html
  codewof/templates/programming/question.html
  codewof/templates/users/achievements.html
  codewof/templates/users/activity_graph.html
  codewof/templates/users/dashboard.html
  codewof/templates/users/user_detail.html
  codewof/tests/codewof_test_data_generator.py
  codewof/tests/features/badges.feature
  codewof/tests/features/points.feature
  codewof/tests/programming/factories.py
  codewof/tests/programming/test_codewof_utils.py
  codewof/tests/programming/test_models.py
  codewof/tests/programming/test_views.py
  codewof/tests/users/test_models.py
  codewof/users/urls.py
  codewof/users/views.py
  dev
  infrastructure/prod-deploy/update-content.sh
  requirements/local.txt
Labels: enhancement

#210 Address issue and reduce number of queries in backdate command
  codewof/programming/codewof_utils.py
  codewof/tests/programming/test_codewof_utils.py
  requirements/base.txt
Labels: bug, dependencies, enhancement

#213 Add print statemements to check status of backdate command
  codewof/programming/codewof_utils.py
  codewof/programming/management/commands/backdate_points_and_badges.py
Labels: bug

#215 Disable single-line reporting of Backdate status
  codewof/programming/codewof_utils.py
Labels: bug

#216 Reduce number of queries during a backdate to bare minimum
  codewof/programming/codewof_utils.py
  codewof/programming/views.py
  codewof/tests/programming/test_codewof_utils.py
  codewof/tests/programming/test_models.py
  codewof/users/views.py
Labels: enhancement

#218 Reimplement backdate command into sampledata command
  .travis.yml
  codewof/general/management/commands/sampledata.py
  codewof/programming/codewof_utils.py
  dev
  infrastructure/dev-deploy/update-content.sh
Labels: enhancement
