Repository uccser/codewof, pull requests merged in 2020-09, with the labels that each got.

#290 Add step by step introduction/tutorial to question pages
  LICENCE-THIRD-PARTY
  codewof/package.json
  codewof/programming/content/en/triangle-pattern/question.md
  codewof/static/css/third-party/introjs-modern.css
  codewof/static/css/third-party/introjs.css
  codewof/static/js/question_types/base.js
  codewof/static/js/question_types/debugging.js
  codewof/static/js/question_types/function.js
  codewof/static/js/question_types/parsons.js
  codewof/static/js/question_types/program.js
  codewof/static/js/third-party/intro.js
  codewof/static/scss/website.scss
  codewof/templates/base.html
  codewof/templates/programming/question.html
  codewof/templates/programming/question_components/editor-python.html
  codewof/templates/programming/question_components/test-case-functions-table.html
  codewof/templates/programming/question_components/test-case-programs-table.html
  third-party-licences/introjs.txt
Labels: content: other, questions

#302 Prevent CSS block being overwritten on style checker pages
  codewof/templates/style/language-statistics.html
  codewof/templates/style/language.html
Labels: bug

#303 Fix bug in page helpers where elements weren't scrolled to properly
  codewof/static/js/question_types/base.js
Labels: bug, questions

#305 Ensure footer is at the bottom of the page even when there is not enough content
  codewof/static/scss/website.scss
  codewof/templates/base.html
Labels: bug
